[package]
name = "fdn-reverb-vst"
version = "0.1.0"
authors = ["Paul Adenot <paul@paul.cx>"]
edition = "2018"

[dependencies]
vst = { git = "https://github.com/rustaudio/vst-rs" }
fdn-reverb = { path = "../fdn-reverb/" }

[lib]
name = "fdnreverb"
crate-type = ["cdylib"]
